### ISSUE TITLE
uap is missing in 2.0.0.14

### ISSUE THREAD

**Issue by DevEddy** [rotorgames/Rg.Plugins.Popup#707]
## 🐛 Bug Report

`Error CS0234 The type or namespace name 'Popup' does not exist in the namespace 'Rg.Plugins.Popup' (are you missing an assembly reference?)`

Package Content 2.0.0.13 (uap included):
![image](https://user-images.githubusercontent.com/7648336/138068804-4f850ee2-2a24-4f2f-ae11-a84817db1c6f.png)

Package content 2.0.0.14 (no uap):
![image](https://user-images.githubusercontent.com/7648336/138068876-37ecb307-3f11-46d3-b79c-73e3a8c14820.png)

### Expected behavior
No error

### Reproduction steps
Use Xamarin.Forms UWP and Rg.Plugins.Popup 2.0.0.14

### Configuration

**Version:** 2.0.0.14

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by PrinceCharles23** [comment]
cannot confirm the source of the issue (since i have not checked) but the behaviour - was introduced in 2.0.0.14 and is working in 2.0.0.13

**Comment by softlion** [comment]
Confirmed. Any workaround except downgrading ?

![image](https://user-images.githubusercontent.com/190756/138448763-7de91c62-a274-44ce-a1ad-47f8cf9ae7fc.png)

**Comment by avorobjovs** [comment]
I confirm this issue.

**Comment by Agredo** [comment]
I can confirm this! Updating directly to 2.0.0.14 will cause this. Downgrading to  2.0.0.13 works!

**Comment by cbs-cbt** [comment]
I confirm this issue.

```
Error CS0234 :
The type or namespace name 'Popup' does not exist in the namespace 'Rg.Plugins.Popup' (are you missing an assembly reference?)
```

When compiling for UWP with version 2.0.0.14

**Comment by FrozDark** [comment]
UWP reference miss confirmed

**Comment by vividos** [comment]
It may be that the build of the NuGet package was done on a Mac, since the UAP assembly is missing in 2.0.0.14. This line takes care that on Mac there is no UWP build:
https://github.com/rotorgames/Rg.Plugins.Popup/blob/4d4d55bc154494bd0400e32c683e6d9aa079b473/Rg.Plugins.Popup/Rg.Plugins.Popup.csproj#L4

**Comment by LuckyDucko** [comment]
Hey guys, sorry for a late reply.

I have updated the latest github package to add on a windows built version of 2.0.0.14. It has 'rebuilt' added within its name. Just remove that and add it manually and hopefully that helps out. I do not have access to the nuget so unfortunately this is the best i can do.

@vividos good call concerning the building issue, lets see if it works out!

**Comment by SBurgos00** [comment]
Is the rebuilt package working for anyone? I still have the same error when using it.

This is what I did to use the new package:
-Download rebuilt package
-Removed ".rebuilt" from the name
-Added a package source for the downloaded package and moved it to the top of the list of sources
-Uninstalled the existing package from all projects
-Clean solution
-Set package manager source to the one I set up above
-Installed the package to all project
-Rebuild

**Comment by kyurkchyan** [comment]
I can confirm this issue as well. As soon as I downgrade to 2.0.0.13 the issue is gone

**Comment by LuckyDucko** [comment]
@SBurgos00 @kyurkchyan 
 do you still get the same error? i did some testing on my windows computer after i built it, just against the rg demo app.
 
I worry i may have missed something obvious, and do apologise that such a large bug has been introduced, i have just had no time for this, let alone the MAUI upgrade i want to be doing. 

I do plan on giving this a renewed focus when i'm on leave in Jan, however, i can give this another look on Sunday, and hope that things work out. 

Can you try just downloading the develop branch and then referencing it as a project in your solution? I know its much less of a solution than with the nuget, however it may get you up and running for the time being

**Comment by SBurgos00** [comment]
@LuckyDucko Later I downloaded the source and added the project to my solution and referenced it in my UWP project. It was able to build and run. I'm going to use it that way for now. It is weird that it didn't work as a Nuget. Don't worry about looking at this on Sunday for just me. Thanks!

**Comment by LuckyDucko** [comment]
@SBurgos00 glad it worked out. I'll give it a test using my own application just to be sure now, if 1 person mentions it, 100 people have had the same issue and have been quiet.

**Comment by kevcrooks** [comment]
@LuckyDucko is it possible to get a nuget release with the fix? We'd like to use it in our build pipeline, but I think manually downloading would only work locally? Glad to find this issue though, we were slightly confused initially!

**Comment by LuckyDucko** [comment]
@kevcrooks 

Ah, i can try and pull one of these out for you, however i wont be able to update on nuget.org, as only  @martijn00 can do that

**Comment by egvijayanand** [comment]
> Is the rebuilt package working for anyone? I still have the same error when using it.
> 
> This is what I did to use the new package: -Download rebuilt package -Removed ".rebuilt" from the name -Added a package source for the downloaded package and moved it to the top of the list of sources -Uninstalled the existing package from all projects -Clean solution -Set package manager source to the one I set up above -Installed the package to all project -Rebuild

How to download the rebuilt package, what's the command to invoke the same?

As I face the same issue with v2.0.0.14 with the UWP project whereas v2.0.0.13 works fine. Want to try the rebuilt package.

**Comment by mfeingol** [comment]
Looks like version 2.1.0 has the same problem.

**Comment by avorobjovs** [comment]
> Looks like version 2.1.0 has the same problem.

No, it isn't. But you need to set the TargetPlatformMinVersion to 10.0.18362.0 for the UWP project. 
Only this UWP version has  2.1.0 packages.

![UWP_2 1 0](https://user-images.githubusercontent.com/7294773/151860645-e8740996-ac9c-4d0b-a33c-c61a25223f38.png)

For some reason, the author forgot to mention this. :)

**Comment by mfeingol** [comment]
@avorobjovs: confirmed, thanks.

**Comment by gceaser** [comment]
I can confirm that after updating to version 2.1.0, I needed to update the TargetPlatformMinVersion to 10.0.18362.0 for the UWP project.  Then everything compiled correctly.  The UWP initialization instructions should probably be updated with this information.

**Comment by egvijayanand** [comment]
Yes, package dependencies in the NuGet page confirm the same.

https://www.nuget.org/packages/Rg.Plugins.Popup/2.1.0#dependencies-tab
